name: ecommerce
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter_svg: ^1.1.6
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^0.13.5
  get_it: ^7.2.0
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  dartz: ^0.10.1
  connectivity_plus: ^3.0.2
  shared_preferences: ^2.0.16
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Poopins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400


  uses-material-design: true
  assets:
    - assets/logo/
    - assets/banner/
    - assets/product/
    - assets/fonts/

 